FROM ubuntu

LABEL maintainer="vmukashi7@gmail.com"

RUN apt-get update &&					\
    apt-get install -y sudo &&			\
    apt-get install -y git &&			\
	apt-get install -y gcc &&			\
	apt-get install -y vim &&			\
	apt-get install -y valgrind