FROM ubuntu

LABEL maintainer="vmukashi7@gmail.com"

RUN apt-get update &&           			\
    apt-get install -y sudo &&				\
    apt-get install -y git &&				\
	apt-get install -y gcc &&				\
	apt-get install -y vim &&				\
	apt-get install -y libsdl2-dev &&		\
	apt-get install -y libsdl2-image-dev &&	\
	apt-get install -y libsdl2-ttf-dev &&	\
	apt-get install -y libsdl2-mixer-dev &&	\
	apt-get install -qqy x11-apps